# Generated by Django 6.0.6 on 2026-06-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.FloatField(default=0, verbose_name='Score total')),
                ('score_skills', models.FloatField(default=0, verbose_name='Score compétences')),
                ('score_experience', models.FloatField(default=0, verbose_name='Score expérience')),
                ('score_education', models.FloatField(default=0, verbose_name='Score formation')),
                ('score_semantic', models.FloatField(default=0, verbose_name='Score sémantique')),
                ('extracted_skills', models.JSONField(default=list, verbose_name='Compétences extraites')),
                ('missing_skills', models.JSONField(default=list, verbose_name='Compétences manquantes')),
                ('extracted_experience', models.IntegerField(default=0, verbose_name='Expérience extraite (années)')),
                ('extracted_education', models.CharField(blank=True, max_length=200)),
                ('recommendation', models.CharField(choices=[('priority', '⭐ Prioritaire'), ('possible', '✅ Possible'), ('reserve', '⚠️ Réserve'), ('rejected', '❌ Rejeté')], default='reserve', max_length=20)),
                ('interview_questions', models.JSONField(default=list, verbose_name="Questions d'entretien")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analyse',
            },
        ),
    ]
