# Generated by Django 6.0.6 on 2026-06-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('description', models.TextField(verbose_name='Description')),
                ('required_skills', models.JSONField(default=list, verbose_name='Compétences requises')),
                ('required_experience', models.IntegerField(default=0, verbose_name='Expérience requise (années)')),
                ('required_education', models.CharField(blank=True, max_length=100, verbose_name="Niveau d'études requis")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('closed', 'Fermée')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'ordering': ['-created_at'],
            },
        ),
    ]
