# Generated by Django 6.0.6 on 2026-06-18 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200, verbose_name='Nom du candidat')),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du candidat')),
                ('cv_file', models.FileField(upload_to='cvs/%Y/%m/', verbose_name='Fichier CV')),
                ('raw_text', models.TextField(blank=True, verbose_name='Texte extrait du CV')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('analyzing', "En cours d'analyse"), ('analyzed', 'Analysé'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='jobs.job', verbose_name="Offre d'emploi")),
            ],
            options={
                'verbose_name': 'CV',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
