# Generated by Django 6.0.6 on 2026-06-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cv_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Cloudinary du CV'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/%Y/%m/', verbose_name='Fichier CV'),
        ),
    ]
