# Generated by Django 6.0.6 on 2026-06-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_cv_url_alter_resume_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name="Message d'erreur"),
        ),
    ]
