# Generated by Django 6.0.6 on 2026-06-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='error_message',
        ),
    ]
